image: docker:latest
services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_IMAGE_VERSION: "vgarcia96/docker:kiwame-api-1.1.0"

docker-build:
  stage: build
  tags:
    - build
  script:
    - docker build -t $DOCKER_IMAGE_VERSION kiwameAPI

docker-push:
  stage: build
  tags: 
    - build
  script:
    - docker login
    - docker push $DOCKER_IMAGE_VERSION