version: '3'
networks:
  app-tier:
    driver: bridge
services:
  mongo:
    image: mongo:4.2.6
    ports:
      - "27777:27017"
    networks:
      - app-tier
  zookeeper:
    image: bitnami/zookeeper:3.6.1
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    tmpfs: "/datalog"
    networks:
      - app-tier
  kafka:
    image: bitnami/kafka:2.4.0
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://192.168.0.159:29092
    depends_on:
      - zookeeper
    networks:
      - app-tier
  api:
    image: vgarcia96/docker:kiwame-api-1.1.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WAIT_HOSTS=mongo:27017, kafka:9092
      - WAIT_AFTER_HOSTS=5
      - CONFIG_ENV=docker
    ports:
      - "8090:8090"
    networks:
      - app-tier
      

